AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create an S3 bucket.

Parameters:
  BucketName:
    Description: Name of the S3 bucket.
    Type: String
  VersioningEnabled:
    Description: Enable versioning for the bucket.
    Type: String
    AllowedValues:
      - "Enabled"
      - "Disabled"
    Default: "Disabled"

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningEnabled
